[package]
name = "cheapazsla-gui"
description = "Desktop application for CheapAzSLA"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "cheapazsla-gui"
path = "src/main.rs"

[dependencies]
cheapazsla-core.workspace = true
gtk = { package = "gtk4", version = "0.9", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.7", features = ["v1_4"] }
async-channel = "2"
png = "0.17"
