[package]
name = "cheapazsla-gui"
description = "Desktop application for CheapAzSLA"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "cheapazsla-gui"
path = "src/main.rs"

[dependencies]
cheapazsla-core.workspace = true
